import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eunni Hompage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> ☆｡ﾟ+.+.ﾟ나는야 체굥은ﾟ+.+.ﾟ｡☆</h1>
        <Image src="/img/whoamI.jpg" width={300} height={300}></Image>
      </main>
    </div>
  )
}
